# fly.toml file generated for fullstackopen-cicd-pokedex on 2023-01-08T10:41:57+02:00

app = "fullstackopen-cicd-pokedex"
kill_signal = "SIGINT"
kill_timeout = 5

[env]
  PORT = "8080"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
  
  [[services.http_checks]]
    grace_period = "5s"
    interval = 10000
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = "2s"
    tls_skip_verify = false

  [[services.scripts_checks]]
    command="./app/health_check.sh"
    grace_period = "3s"
    interval = "5s"
    restart_limit = 0
    timeout = "2s"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"
