name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world_job:
    runs-on: ubuntu-20.04
    steps:
      - name: say hello
        run: |
          echo "Hello World!"
      - name: print date
        run: |
          date
      - name: print current directory content
        run: |
          ls -l